### ISSUE TITLE
Tiny issue with text overflow on narrow screens in the GitHub integration prompt

### ISSUE THREAD

**Issue by antonmoiseev** [zeit/now-cloud#61]
Here is how it looks like on iPhone 7 Plus screen size:
![github-integration-issue](https://user-images.githubusercontent.com/182853/42461562-d19b1680-83b1-11e8-9a27-02b1dc709b62.png)
A quick change that could fix it:
```css
.message {
  overflow-y: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```
![github-integration-issue-possible-fix](https://user-images.githubusercontent.com/182853/42461838-95f1f170-83b2-11e8-91c4-7a38644aae6e.png)

Thanks!
